import prisma from '../src/lib/prisma.ts'

const tickets: {
  subject: string
  body: string
  fromName: string
  fromEmail: string
  toEmail: string
  status: 'open' | 'resolved' | 'closed'
  category: 'general_question' | 'technical_question' | 'refund_request' | null
  createdAt: Date
}[] = [
  // --- Technical Questions ---
  {
    subject: 'Cannot log in after password reset',
    body: "Hi, I reset my password but I'm still getting an 'invalid credentials' error when I try to log in. I've tried three different browsers and cleared my cache. Nothing works.",
    fromName: 'Alice Nguyen',
    fromEmail: 'alice.nguyen@acmecorp.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(0),
  },
  {
    subject: 'Two-factor authentication codes not working',
    body: "My 2FA codes from the authenticator app are being rejected. I've confirmed the time on my phone is synced. This started happening today.",
    fromName: 'Marcus Webb',
    fromEmail: 'marcus.webb@techflow.io',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(1),
  },
  {
    subject: 'API returning 500 errors intermittently',
    body: "We're seeing random 500 errors from the /api/orders endpoint about once every 50 requests. It started around 3pm EST yesterday. Our logs show no pattern.",
    fromName: 'Priya Sharma',
    fromEmail: 'priya@buildspace.dev',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(1),
  },
  {
    subject: 'CSV export produces empty file',
    body: "When I click 'Export to CSV' on the reports page, the file downloads but it's completely empty except for the header row. Happens on all report types.",
    fromName: 'Jordan Lee',
    fromEmail: 'jordan.lee@finworks.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(2),
  },
  {
    subject: 'Mobile app crashes on startup on iOS 17',
    body: "After updating to iOS 17.4, the app crashes immediately on launch. I've reinstalled three times. Other users on my team have the same issue.",
    fromName: 'Sofia Petrov',
    fromEmail: 'sofia.petrov@cloudnine.co',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(2),
  },
  {
    subject: 'File upload fails for files over 8MB',
    body: "I'm trying to upload a 12MB PDF and keep getting 'Upload failed' with no further detail. Files under 8MB work fine. Our plan says we support up to 25MB.",
    fromName: 'David Park',
    fromEmail: 'dpark@stellarworks.net',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(3),
  },
  {
    subject: 'Dashboard not rendering on Firefox 124',
    body: "The main dashboard shows a blank screen in Firefox 124. Chrome and Safari work fine. Console shows: 'TypeError: Cannot read properties of undefined (reading map)'.",
    fromName: 'Emma Thornton',
    fromEmail: 'emma.thornton@novabrand.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(3),
  },
  {
    subject: 'Webhook events stopped being delivered',
    body: "Our webhook endpoint stopped receiving events around 6am UTC today. The endpoint is healthy — we tested it manually. No changes on our side.",
    fromName: 'Liam O\'Brien',
    fromEmail: 'liam@devpulse.io',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(4),
  },
  {
    subject: 'SSO login returns SAML assertion error',
    body: "Trying to set up SSO with Okta and getting 'SAML assertion not valid yet' on the callback. Our IdP clock is synced. Entity ID and ACS URL are both correct.",
    fromName: 'Rachel Kim',
    fromEmail: 'rachel.kim@enterprise-co.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(5),
  },
  {
    subject: 'Email notifications stopped sending',
    body: "Users on our account stopped receiving email notifications for new assignments 48 hours ago. Our MX records haven't changed. Notifications show as 'sent' in your UI.",
    fromName: 'Tom Bradley',
    fromEmail: 'tbradley@redwoodops.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(5),
  },
  {
    subject: 'Search returning irrelevant results',
    body: "Searching for 'Q1 report' returns items from 2019 and completely unrelated documents. The index seems stale or broken. Worked fine two weeks ago.",
    fromName: 'Nina Castillo',
    fromEmail: 'nina.castillo@meridian-group.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(6),
  },
  {
    subject: '403 Forbidden on reports endpoint',
    body: "I'm an admin on the account but getting 403 when accessing /reports/financial. Other admins can access it fine. My role hasn't changed.",
    fromName: 'Owen Fletcher',
    fromEmail: 'o.fletcher@alphastream.co',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(7),
  },
  {
    subject: 'Slack integration stopped posting updates',
    body: "The Slack integration was working perfectly for 3 months and stopped posting to #support-alerts yesterday. The bot is still in the channel and has permissions.",
    fromName: 'Claire Zhang',
    fromEmail: 'claire.zhang@momentum-inc.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(8),
  },
  {
    subject: 'Data not syncing across devices',
    body: "Changes I make on desktop don't show up on mobile for 10–15 minutes. This is new behavior — it used to sync in seconds. We have 8 users experiencing this.",
    fromName: 'Ethan Brooks',
    fromEmail: 'ebrooks@sunrisetech.co',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(9),
  },
  {
    subject: 'Bulk import rejecting valid CSV format',
    body: "I'm trying to import 500 contacts via CSV using your template. It fails on row 1 with 'invalid date format' even though dates are in YYYY-MM-DD exactly as documented.",
    fromName: 'Amara Osei',
    fromEmail: 'amara.osei@springpath.org',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(10),
  },
  {
    subject: 'Rate limit errors despite low request volume',
    body: "We're hitting 429 rate limit errors but our dashboard shows we're only at 12% of our quota. We have the Growth plan. This is blocking production.",
    fromName: 'Sam Okafor',
    fromEmail: 'sam@crestline-dev.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(11),
  },
  {
    subject: 'Report scheduler stopped running at midnight',
    body: "Scheduled reports were configured to run at midnight UTC daily. They ran fine for 2 weeks, then stopped 4 days ago. Timezone is set correctly in settings.",
    fromName: 'Isabella Moore',
    fromEmail: 'imoore@graphite-partners.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(12),
  },
  {
    subject: 'Custom domain setup not working',
    body: "I've added the CNAME records exactly as documented but portal.ourcompany.com still resolves to the default domain. DNS propagation shows the records are live.",
    fromName: 'Henry Walsh',
    fromEmail: 'henry.walsh@ironbay.io',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(13),
  },
  {
    subject: 'PDF generation timing out for large reports',
    body: "Generating PDFs for reports with 200+ rows times out after 30 seconds. Smaller reports (under 50 rows) work fine. This is a regression from last week.",
    fromName: 'Zoe Adeyemi',
    fromEmail: 'z.adeyemi@clearfield-analytics.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(14),
  },
  {
    subject: 'OAuth token refresh loop',
    body: "Our integration keeps getting logged out every 60 seconds. The refresh token flow seems to generate a new access token but then immediately invalidates it.",
    fromName: 'Felix Ramos',
    fromEmail: 'felix.ramos@looptrace.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(16),
  },
  // --- General Questions ---
  {
    subject: 'How do I add additional team members?',
    body: "We want to onboard 5 more agents to our account. I can see the Users section but don't see an 'Invite' button. Do I need a higher plan for this?",
    fromName: 'Grace Liu',
    fromEmail: 'grace.liu@orbita-labs.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(0),
  },
  {
    subject: 'What are your support hours?',
    body: "We're based in Sydney, Australia. Can you confirm your support hours in AEST? We need to know when live chat is available.",
    fromName: 'Callum Reeves',
    fromEmail: 'creeves@downunder-digital.com.au',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(1),
  },
  {
    subject: 'Can I export all my historical data?',
    body: "We've been using your platform for 2 years and want a full export of all tickets, contacts, and audit logs before considering a migration. What format is available?",
    fromName: 'Natalie Cross',
    fromEmail: 'natalie@vantagepoint-ops.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(2),
  },
  {
    subject: 'Do you have a public API?',
    body: "We're looking to integrate your platform with our internal tools. Is there a REST or GraphQL API available? Where can I find documentation and rate limits?",
    fromName: 'Lucas Berg',
    fromEmail: 'lucas.berg@neonstack.dev',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(3),
  },
  {
    subject: 'Do you offer a nonprofit discount?',
    body: "We're a registered 501(c)(3) nonprofit and are interested in your Team plan. Do you offer discounted pricing for nonprofits? If so, what documentation do you need?",
    fromName: 'Diane Foster',
    fromEmail: 'dfoster@brightpath-foundation.org',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(4),
  },
  {
    subject: 'Difference between admin and agent roles',
    body: "We're setting up our team and I want to understand the permissions difference between admin and agent roles before assigning access. Can you share a comparison?",
    fromName: 'Aaron Simmons',
    fromEmail: 'asimmons@verdant-studios.co',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(5),
  },
  {
    subject: 'Can I import contacts from HubSpot?',
    body: "We have 3,000 contacts in HubSpot and want to migrate them here. Is there a native HubSpot integration or do I need to export/import manually?",
    fromName: 'Megan Hart',
    fromEmail: 'mhart@fusionwave.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(6),
  },
  {
    subject: 'How does billing work for mid-cycle upgrades?',
    body: "We want to upgrade from Starter to Growth mid-month. Are we charged the pro-rated difference immediately, or does it apply at the next billing cycle?",
    fromName: 'Paul Nakamura',
    fromEmail: 'paul.nakamura@axiom-corp.jp',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(7),
  },
  {
    subject: 'Are there HIPAA-compliant hosting options?',
    body: "We work with patient data and need HIPAA-compliant infrastructure. Do you offer a BAA? Are your servers hosted in the US?",
    fromName: 'Sandra Lowe',
    fromEmail: 'slowe@carepath-systems.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(8),
  },
  {
    subject: 'What is the data retention policy?',
    body: "Our compliance team wants to know how long you retain deleted records. Is there a grace period before permanent deletion? Can we request immediate deletion?",
    fromName: 'James Holloway',
    fromEmail: 'j.holloway@truestride-legal.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(9),
  },
  {
    subject: 'Is there an SLA for the Growth plan?',
    body: "We're evaluating whether to upgrade to Growth for the SLA guarantees. What are the guaranteed response and resolution times for P1 incidents?",
    fromName: 'Hana Yoshida',
    fromEmail: 'hyoshida@bluefield-ventures.jp',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(10),
  },
  {
    subject: 'How do custom fields work?',
    body: "I want to add a 'Department' field to tickets. I found 'Custom Fields' in settings but I'm not sure if I set it to text, dropdown, or multi-select for our use case.",
    fromName: 'Olivia Santos',
    fromEmail: 'o.santos@wavefront-media.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(11),
  },
  {
    subject: 'Can we white-label the customer portal?',
    body: "Our customers currently see your branding on the support portal. Can we replace the logo and colors with our own? Is this available on the current plan?",
    fromName: 'Chris Dupont',
    fromEmail: 'cdupont@vertexsuite.fr',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(12),
  },
  {
    subject: 'How do I archive old tickets?',
    body: "We have thousands of resolved tickets from 2022 and 2023 cluttering our dashboard. Is there a bulk archive feature? We want to keep them but hide from default views.",
    fromName: 'Rita Adkins',
    fromEmail: 'rita.adkins@cornerstone-retail.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(13),
  },
  {
    subject: 'Can multiple agents work on one ticket simultaneously?',
    body: "Sometimes a ticket needs input from both our billing and tech teams at the same time. Is there a collaborative mode, or does one agent need to hand off to the other?",
    fromName: 'Derek Owens',
    fromEmail: 'derek.owens@peakline-services.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(15),
  },
  {
    subject: 'Do you support dark mode?',
    body: "Several of our agents work long shifts and have asked about a dark mode option. Is it available or on the roadmap?",
    fromName: 'Jenny Marsh',
    fromEmail: 'jenny.marsh@nocturne-design.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(17),
  },
  {
    subject: 'How to set up automatic ticket routing?',
    body: "We want tickets with the word 'invoice' in the subject to go directly to our billing team. Is there a rule or automation engine I can configure for this?",
    fromName: 'Victor Chen',
    fromEmail: 'vchen@lighthouse-finance.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(18),
  },
  {
    subject: 'What happens to data if I downgrade my plan?',
    body: "We're considering moving from Growth back to Starter temporarily. Will we lose any data or features immediately, or is there a grace period?",
    fromName: 'Anna Bergström',
    fromEmail: 'a.bergstrom@nordic-solutions.se',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(19),
  },
  {
    subject: 'Is there mobile app for agents?',
    body: "Our agents are sometimes on the go and need to respond to urgent tickets from their phones. Is there a mobile app for iOS and Android, or just a web interface?",
    fromName: 'Bobby Turner',
    fromEmail: 'bturner@rapidfield.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(20),
  },
  {
    subject: 'Can I set up auto-reply for off-hours?',
    body: "We want customers to receive an automatic reply outside of 9am–6pm EST saying we'll respond the next business day. Is there an out-of-office auto-reply feature?",
    fromName: 'Tara Singh',
    fromEmail: 'tara.singh@pinecrest-consulting.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(22),
  },
  // --- Refund Requests ---
  {
    subject: 'Charged twice for March subscription',
    body: "My credit card was charged $149 on March 1st and again on March 3rd for the same subscription period. Please refund the duplicate charge.",
    fromName: 'Patrick Moore',
    fromEmail: 'pmoore@clearview-tech.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'refund_request',
    createdAt: daysAgo(1),
  },
  {
    subject: 'Charged after canceling subscription',
    body: "I canceled my subscription on February 28th through the billing settings, received a confirmation email, but was still charged $79 on March 1st. Please refund.",
    fromName: 'Laura Hicks',
    fromEmail: 'l.hicks@personalfinance-blog.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'refund_request',
    createdAt: daysAgo(3),
  },
  {
    subject: 'Accidentally purchased annual plan instead of monthly',
    body: "I meant to select the monthly plan but accidentally clicked the annual option and was charged $1,188 upfront. I noticed within 10 minutes. Can I get a refund and switch to monthly?",
    fromName: 'Brian Kessler',
    fromEmail: 'bkessler@workshop-media.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'refund_request',
    createdAt: daysAgo(4),
  },
  {
    subject: 'Refund for unused months after downgrade',
    body: "I prepaid for an annual Growth plan and downgraded to Starter last month. I have 7 months remaining and would like a pro-rated refund for the unused period.",
    fromName: 'Michelle Stone',
    fromEmail: 'michelle.stone@driftwood-creative.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'refund_request',
    createdAt: daysAgo(6),
  },
  {
    subject: 'Charged wrong plan amount — pricing discrepancy',
    body: "Your website showed the Growth plan at $99/mo but I was charged $129/mo. I have a screenshot of the pricing page at the time of purchase. Please correct and refund the difference.",
    fromName: 'Kevin Marsh',
    fromEmail: 'kevin.marsh@pixelrush.co',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'refund_request',
    createdAt: daysAgo(7),
  },
  {
    subject: 'Request refund — service was down during our event',
    body: "Your platform was down for 6 hours on March 15th during our product launch event. This significantly impacted our team. We'd like a partial refund for the downtime.",
    fromName: 'Sarah Okonkwo',
    fromEmail: 'sarah.okonkwo@launchpad-events.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'refund_request',
    createdAt: daysAgo(9),
  },
  {
    subject: 'Unauthorized charge on company card',
    body: "Our finance team flagged a charge of $299 from your company on our corporate card. We don't have an account with this email. Please investigate and refund immediately.",
    fromName: 'James O\'Sullivan',
    fromEmail: 'josullivan@enterprise-audit.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'refund_request',
    createdAt: daysAgo(10),
  },
  {
    subject: 'Charged after free trial ended — no warning',
    body: "I signed up for a 14-day free trial and expected to be prompted before being charged. I was billed $79 on day 15 with no email reminder. Please refund.",
    fromName: 'Lily Fernandez',
    fromEmail: 'lily.f@startuplife.io',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'refund_request',
    createdAt: daysAgo(12),
  },
  {
    subject: 'Double-billed for add-on feature',
    body: "I see two line items for 'Advanced Analytics Add-on' on my March invoice — one for $29 and one for $29. I only have one account. Please refund the duplicate.",
    fromName: 'Nia Chambers',
    fromEmail: 'nia.chambers@analyticsedge.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'refund_request',
    createdAt: daysAgo(14),
  },
  {
    subject: 'Account was suspended but still being charged',
    body: "Our account was suspended on February 10th for a payment failure. We fixed the payment method but then the account stayed suspended and we were charged again in March.",
    fromName: 'Troy Hammond',
    fromEmail: 'troy@hammondgroup.net',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'refund_request',
    createdAt: daysAgo(16),
  },
  // --- Mixed statuses, more technical ---
  {
    subject: 'Permissions not propagating to subfolders',
    body: "I set folder-level permissions for a user but they can still access all subfolders. Changing and re-saving permissions has no effect.",
    fromName: 'Cynthia Park',
    fromEmail: 'cpark@talentpath-hr.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(20),
  },
  {
    subject: 'Graph API throwing authentication error',
    body: "Getting 401 on /v2/graph with a fresh token. Token works fine on other endpoints. Started after your platform update last Tuesday.",
    fromName: 'Adam Holloway',
    fromEmail: 'adam.holloway@circuitworks.io',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(21),
  },
  {
    subject: 'Date filter returning wrong date range',
    body: "Filtering tickets by 'last 30 days' seems to return results from the last 60 days. We're in UTC+8 and wondering if there's a timezone offset bug.",
    fromName: 'Wei Liang',
    fromEmail: 'wei.liang@eastgate-tech.cn',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(22),
  },
  {
    subject: 'Notification badges not clearing after reading',
    body: "The unread badge on the notifications bell stays at 12 even after I've opened and read all notifications. Logging out and back in temporarily fixes it.",
    fromName: 'Fatima Diallo',
    fromEmail: 'fdiallo@sahara-connect.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(23),
  },
  {
    subject: 'Print layout broken — content overflows page',
    body: "When printing a ticket detail view, the content bleeds off the right edge of the page. This only happens with tickets that have more than 3 attachments.",
    fromName: 'George Mercer',
    fromEmail: 'g.mercer@hardcopy-legal.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(24),
  },
  {
    subject: 'Autocomplete suggests deleted users',
    body: "When assigning tickets, the agent autocomplete still shows users I've deleted from the account. Selecting them throws an error.",
    fromName: 'Valerie Dunn',
    fromEmail: 'valerie.dunn@prism-media.co',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(25),
  },
  {
    subject: 'Timezone setting ignored for reminders',
    body: "I set my timezone to PST but reminders still fire at UTC times. A reminder set for 9am PST fires at 9am UTC (which is 1am PST for me).",
    fromName: 'Marcus Hill',
    fromEmail: 'mhill@coastalops.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(26),
  },
  {
    subject: 'Canned responses not saving',
    body: "Every time I create a new canned response and save it, it disappears after I navigate away. I've tried three different browsers.",
    fromName: 'Isabelle Fontaine',
    fromEmail: 'ifontaine@paristech.fr',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(28),
  },
  {
    subject: 'Report drill-down shows wrong ticket count',
    body: "The summary report says I have 145 open tickets, but when I click to drill down, only 132 appear. The numbers don't add up and this is causing audit issues.",
    fromName: 'Andrew Pearce',
    fromEmail: 'andrew.pearce@auditright.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'technical_question',
    createdAt: daysAgo(30),
  },
  {
    subject: 'Language setting defaults to English after reload',
    body: "I change the interface language to French, save successfully, but after refreshing the page it reverts to English. This happens every time.",
    fromName: 'Béatrice Moreau',
    fromEmail: 'bmoreau@solutions-france.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'technical_question',
    createdAt: daysAgo(32),
  },
  // --- More general questions ---
  {
    subject: 'Can I restrict agents to specific ticket queues?',
    body: "We have a billing team and a tech team. I want billing agents to only see billing tickets and tech agents to only see tech tickets. Is queue-level access control available?",
    fromName: 'Anthony Rivers',
    fromEmail: 'arivers@riversconsulting.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(24),
  },
  {
    subject: 'How do I set ticket priority levels?',
    body: "I see there are status fields but I need to mark some tickets as High/Medium/Low priority separately from status. Is there a priority field or do I use a custom field?",
    fromName: 'Monica Vega',
    fromEmail: 'mvega@primoops.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(25),
  },
  {
    subject: 'Does the platform support multiple inboxes?',
    body: "We have three support email addresses: support@, billing@, and enterprise@. Can we route each one into a separate inbox/queue in your platform?",
    fromName: 'Dylan Briggs',
    fromEmail: 'd.briggs@triomail.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(27),
  },
  {
    subject: 'How long does onboarding take?',
    body: "We're migrating from Zendesk and want to know the realistic timeline from signing up to being fully operational with our 15-agent team.",
    fromName: 'Carla Washington',
    fromEmail: 'cwashington@nextgencustomer.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(29),
  },
  {
    subject: 'Can customers see ticket status from their end?',
    body: "When a customer submits a ticket, can they track its status (open, in progress, resolved) somewhere, or do they just wait for email updates?",
    fromName: 'Oscar Fleming',
    fromEmail: 'oscar.fleming@enduser-labs.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(31),
  },
  {
    subject: 'Is there an audit log?',
    body: "Our compliance team needs to track which agent made changes to which tickets, and when. Is there an activity/audit log with timestamps and user attribution?",
    fromName: 'Frances Holden',
    fromEmail: 'fholden@compliance360.com',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'general_question',
    createdAt: daysAgo(33),
  },
  {
    subject: 'Can I set up SLA breach alerts?',
    body: "We want an alert (email or Slack) when a ticket is approaching its SLA deadline. Is there a built-in SLA alert system or do we need to set this up with webhooks?",
    fromName: 'Nathan Griffith',
    fromEmail: 'ngriffith@sla-masters.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'general_question',
    createdAt: daysAgo(35),
  },
  // --- More refund requests ---
  {
    subject: 'Refund — feature we paid for was removed without notice',
    body: "We upgraded to Growth specifically for the Advanced Analytics feature. Two weeks after upgrading, that feature was removed in an update with no notice. We'd like a refund.",
    fromName: 'Gregory Nash',
    fromEmail: 'gnash@datadriven-co.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'refund_request',
    createdAt: daysAgo(18),
  },
  {
    subject: 'Wrong currency charged — should be EUR not USD',
    body: "Our account is set to EUR billing but we were charged in USD at an unfavorable rate. We were charged $99 USD instead of €89 EUR. Please correct.",
    fromName: 'Elena Müller',
    fromEmail: 'elena.mueller@europework.de',
    toEmail: 'support@helpdesk.com',
    status: 'resolved',
    category: 'refund_request',
    createdAt: daysAgo(20),
  },
  {
    subject: 'Charged for seats we removed last month',
    body: "We removed 3 agent seats from our account on March 5th. The March invoice still shows 12 seats instead of 9. Please refund the difference for 3 seats × 26 days.",
    fromName: 'Paul Garrett',
    fromEmail: 'pgarrett@midtown-ops.com',
    toEmail: 'support@helpdesk.com',
    status: 'open',
    category: 'refund_request',
    createdAt: daysAgo(22),
  },
  // --- Closed/older tickets for variety ---
  {
    subject: 'Integration with Jira not creating issues',
    body: "The Jira integration used to create issues automatically for P1 tickets. It stopped working after we migrated to Jira Cloud. Nothing has changed on our auth settings.",
    fromName: 'Luke Barton',
    fromEmail: 'luke.barton@devops-core.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(35),
  },
  {
    subject: 'Can attachments be set to expire after 30 days?',
    body: "For security reasons, we want file attachments in tickets to automatically expire after 30 days. Is there an attachment retention policy setting?",
    fromName: 'Vivian Chu',
    fromEmail: 'vchu@datasafe-inc.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(36),
  },
  {
    subject: 'How do I set a default assignee for new tickets?',
    body: "We want all new tickets to be assigned to our triage agent automatically. Is there a default assignment rule I can configure in settings?",
    fromName: 'Rosa Iglesias',
    fromEmail: 'rosa.iglesias@client-first.es',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(38),
  },
  {
    subject: 'Dashboard widget shows NaN for average response time',
    body: "The 'Avg. First Response Time' widget on the dashboard shows NaN. It started showing this after we had a day with zero tickets last Friday.",
    fromName: 'Trevor Mason',
    fromEmail: 'tmason@metricview.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(40),
  },
  {
    subject: 'Bulk close tickets not working for large selections',
    body: "Selecting 50+ tickets and clicking 'Close all' spins for 30 seconds then shows an error. Closing 10 at a time works fine.",
    fromName: 'Fiona Campbell',
    fromEmail: 'fcampbell@volumedesk.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(42),
  },
  {
    subject: 'Refund for downtime during launch week',
    body: "Your service experienced multiple outages during our product launch week in February. Each outage lasted 2–4 hours. We request a 20% monthly credit per your SLA.",
    fromName: 'Marcus Allen',
    fromEmail: 'marcus.allen@launchteam.io',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'refund_request',
    createdAt: daysAgo(44),
  },
  {
    subject: 'Can I set conditional ticket fields?',
    body: "I want to show a 'Product Version' field only when the category is 'Technical Question'. Is there a conditional field logic feature?",
    fromName: 'Aisha Bello',
    fromEmail: 'aisha.bello@uicraft-studio.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(46),
  },
  {
    subject: 'Ticket merge losing internal notes',
    body: "When I merge two tickets, the internal notes from the secondary ticket disappear from the merged ticket. Only the public replies carry over.",
    fromName: 'Ross Whitfield',
    fromEmail: 'r.whitfield@helpdeskpro.co.uk',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(48),
  },
  {
    subject: 'Reply templates not respecting custom variables',
    body: "I created a template with {{customer.first_name}} but it's rendering literally as '{{customer.first_name}}' instead of the actual name. Variables work in other contexts.",
    fromName: 'Diana Tran',
    fromEmail: 'dtran@templatefirst.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(50),
  },
  {
    subject: 'Refund — account created by mistake',
    body: "A team member accidentally created a second account for our organization and the card on file was charged. We want to close the duplicate account and receive a full refund.",
    fromName: 'Simon Grant',
    fromEmail: 'simon.grant@parallax-tech.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'refund_request',
    createdAt: daysAgo(52),
  },
  {
    subject: 'How do I transfer account ownership?',
    body: "Our original admin is leaving the company. How do I transfer the owner role to a different email address? I don't want to lose access to billing and settings.",
    fromName: 'Samantha Fox',
    fromEmail: 's.fox@brightwave-agency.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(54),
  },
  {
    subject: 'Keyboard shortcuts reference',
    body: "Is there a keyboard shortcut cheat sheet for the ticket interface? I can navigate faster with keyboard shortcuts and want to know what's available.",
    fromName: 'Joel Hartley',
    fromEmail: 'joel.hartley@speedwork.co',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(56),
  },
  {
    subject: 'Real-time chat integration support',
    body: "Do you integrate with Intercom or Drift for real-time chat? We want chat conversations to automatically create a ticket when unresolved.",
    fromName: 'Naomi Bates',
    fromEmail: 'nbates@liveconvert.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(58),
  },
  {
    subject: 'Spam filter blocking legitimate customer emails',
    body: "Several customer tickets from a specific domain (clientco.com) are being automatically marked as spam and closed. They're legitimate customers.",
    fromName: 'Tyler Ross',
    fromEmail: 'tyler.ross@filterfix.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(60),
  },
  {
    subject: 'Webhook signature verification failing',
    body: "We're verifying webhook signatures using your documented HMAC-SHA256 method but every request fails verification. We've triple-checked our secret.",
    fromName: 'Ingrid Sorenson',
    fromEmail: 'ingrid.sorenson@webhooksafe.no',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(62),
  },
  {
    subject: 'Can I see who viewed a ticket?',
    body: "For accountability, we want to see a log of which agents have viewed a specific ticket. Is there a 'seen by' log or read receipt feature?",
    fromName: 'Conrad Mills',
    fromEmail: 'cmills@auditlane.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(64),
  },
  {
    subject: 'Custom report builder missing date grouping',
    body: "The custom report builder doesn't have a 'group by week' option, only day and month. For our weekly sprint reviews we need weekly aggregation.",
    fromName: 'Priscilla James',
    fromEmail: 'pjames@sprintdesk.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(65),
  },
  {
    subject: 'International phone number format rejected',
    body: "I can't save a contact with a UK phone number (+44 7700 900123). The field only accepts US formats. This is a problem for our international clients.",
    fromName: 'Charlotte Hughes',
    fromEmail: 'c.hughes@globaldesk.co.uk',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(66),
  },
  {
    subject: 'How do merge tags work in email templates?',
    body: "I want to use {{agent.name}} in my email reply template so it's signed automatically. I read the docs but can't get it to render — it shows as literal text.",
    fromName: 'Damien Frost',
    fromEmail: 'dfrost@templatepro.io',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(68),
  },
  {
    subject: 'Ticket number sequence reset after migration',
    body: "After migrating from our old system, ticket numbers started from #1 again. Our customers reference old ticket numbers in follow-up emails and it's causing confusion.",
    fromName: 'Nelson Cruz',
    fromEmail: 'ncruz@migrationco.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(70),
  },
  {
    subject: 'How to configure round-robin assignment?',
    body: "We want new tickets to be assigned in a round-robin fashion across our 6 available agents. Is there an automatic round-robin assignment rule I can set up?",
    fromName: 'Gina Powell',
    fromEmail: 'gpowell@fairshare-support.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(72),
  },
  {
    subject: 'Can I require a category on ticket submission?',
    body: "We want to make the 'Category' field mandatory so tickets can't be submitted without one. Is there a way to mark fields as required in the ticket form?",
    fromName: 'Teresa Moon',
    fromEmail: 'teresa.moon@fieldops.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(74),
  },
  {
    subject: 'Refund — paid for integration that was never released',
    body: "We upgraded to Enterprise to access the Salesforce integration announced in your roadmap. It's been 8 months with no release date. We want a refund for the premium we paid.",
    fromName: 'Harold Stephens',
    fromEmail: 'hstephens@crmneeds.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'refund_request',
    createdAt: daysAgo(75),
  },
  {
    subject: 'Ticket watcher notifications not working',
    body: "I added myself as a watcher on 12 tickets but I'm not getting email notifications when they're updated. My notification preferences allow watcher emails.",
    fromName: 'Sylvia Grant',
    fromEmail: 'sgrant@watcherdesk.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(77),
  },
  {
    subject: 'GDPR data deletion request',
    body: "We received a GDPR deletion request from a customer. I need to confirm that deleting their contact also removes all associated ticket data and prevents future processing.",
    fromName: 'Petra Kovač',
    fromEmail: 'pkovac@gdpr-advisory.eu',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(79),
  },
  {
    subject: 'Agent availability status not updating in real time',
    body: "When an agent sets themselves as 'Away', it takes 5–10 minutes for the status to update for other agents. This breaks our handoff process.",
    fromName: 'Quincy Burns',
    fromEmail: 'qburns@realtimesupport.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(80),
  },
  {
    subject: 'How do I clone a ticket workflow?',
    body: "We have a complex ticket workflow with 12 automations. We want to duplicate it for a new brand we're launching without building it from scratch.",
    fromName: 'Cassidy Holt',
    fromEmail: 'cassidy.holt@multibrand-ops.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(82),
  },
  {
    subject: 'Ticket subject line truncated in email replies',
    body: "When agents reply to tickets, the email subject gets truncated at 80 characters. Our ticket subjects are often longer and customers can't identify which ticket the reply is for.",
    fromName: 'Lionel Porter',
    fromEmail: 'lporter@maildept.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(84),
  },
  {
    subject: 'No email received for password reset',
    body: "I requested a password reset 3 times and never received the email. I've checked spam and junk folders. My email address is confirmed in the account settings.",
    fromName: 'Monique Stern',
    fromEmail: 'mstern@designfield.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(86),
  },
  {
    subject: 'Subscription upgrade not taking effect',
    body: "I upgraded from Starter to Growth 3 days ago, was charged successfully, but still see Starter features. The billing page shows Growth plan active.",
    fromName: 'Tyler Huang',
    fromEmail: 'tyler.huang@upgrower.co',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'technical_question',
    createdAt: daysAgo(88),
  },
  {
    subject: 'How to track first contact resolution rate?',
    body: "Is there a built-in report for First Contact Resolution (FCR) rate? I need this metric for our monthly executive review.",
    fromName: 'Patricia Owens',
    fromEmail: 'patricia.owens@kpitrack.com',
    toEmail: 'support@helpdesk.com',
    status: 'closed',
    category: 'general_question',
    createdAt: daysAgo(90),
  },
]

function daysAgo(n: number): Date {
  const d = new Date()
  d.setDate(d.getDate() - n)
  // Spread times throughout the day for realistic variety
  d.setHours(Math.floor(Math.random() * 14) + 7)
  d.setMinutes(Math.floor(Math.random() * 60))
  d.setSeconds(Math.floor(Math.random() * 60))
  return d
}

async function main() {
  console.log(`Seeding ${tickets.length} tickets…`)

  let created = 0
  for (const ticket of tickets) {
    const messageId = `seed-${Date.now()}-${Math.random().toString(36).slice(2)}@mail.example.com`
    await prisma.ticket.create({
      data: {
        ...ticket,
        messageId,
        toEmail: ticket.toEmail,
      },
    })
    created++
  }

  console.log(`Done — created ${created} tickets.`)
  await prisma.$disconnect()
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
